repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    - id: fmt
    - id: cargo-check
